trigger:
  tags:
    include:
      - v*

pool:
  vmImage: 'ubuntu-16.04'

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: install_requirements
        displayName: "Install requirements"
        pool:
          vmImage: "ubuntu-16.04"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.x"
            displayName: "Use Python 3.x"
          - script: python --version
            displayName: "Check Python version"


  - stage: package
    displayName: Package
    jobs:
      - job: run_setup
        displayName: "Run setup"
        pool:
          vmImage: "ubuntu-16.04"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.x"
            displayName: "Use Python 3.x"
          - script: python -m pip install --upgrade pip setuptools wheel twine
            displayName: "Install tools"
          - script: python setup.py sdist bdist_wheel
            displayName: "Create wheel"
          - task: TwineAuthenticate@1
            inputs:
              pythonUploadServiceConnection: 'pypi-test'

          - script: 'twine upload --repository testpypi dist/'



